config/routes.rb
Pairer::Engine.routes.draw do
  get :sign_in, to: "sessions#sign_in"
  post :sign_in, to: "sessions#sign_in"
  get :sign_out, to: "sessions#sign_out"

  resources :boards, controller: :boards, except: [:new, :edit] do
    member do
      post :shuffle
      post :create_person
      post :lock_person
      delete :delete_person
      post :create_group
      post :lock_group
      delete :delete_group
      post :update_group
    end
  end

  get '/robots', to: 'application#robots', constraints: ->(req){ req.format == :text }

  match '*a', to: 'application#render_404', via: :get

  get "/", to: "boards#index"

  root "boards#index"
end

app/models/pairer/application_record.rb
module Pairer
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true

    after_create do
      salt = Pairer.config.hash_id_salt
      pepper = self.class.table_name

      self.update_columns(public_id: Hashids.new("#{salt}_#{pepper}", 8).encode(id))
    end

    validates :public_id, uniqueness: {case_sensitive: true, allow_blank: true}

    def to_param
      try(:public_id) || id
    end

    if Rails::VERSION::STRING.to_f < 7
      def in_order_of(column, order_array)
        Arel.sql(
          <<~SQL
            case #{table_name}.#{column}
            #{order_array.map_with_index{|x, i| "when '#{x}' then #{i+1}"}.join(" ")}
            else #{order_array.size+1}
            end
          SQL
        )
      end
    end

  end
end

app/models/pairer/group.rb
module Pairer
  class Group < ApplicationRecord
    belongs_to :board, class_name: "Pairer::Board"

    validates :board_id, presence: true
    validates :board_iteration_number, presence: true, numericality: { only_integer: true, minimum: 0 }

    def person_ids=(val)
      if val.is_a?(Array)
        sanitized_array = val.map{|x| x.presence&.strip }.uniq(&:downcase).compact

        if !new_record?
          sanitized_array = sanitized_array.intersection(board.people.map(&:public_id)) ### This may slow the query down
        end

        self[:person_ids] = sanitized_array.join(";;")
      else
        raise "invalid behaviour"
      end
    end

    def person_ids_array
      self[:person_ids]&.split(";;") || []
    end

    def roles=(val)
      if val.is_a?(Array)
        sanitized_array = val.map{|x| x.presence&.strip }.uniq(&:downcase).compact

        if !new_record?
          sanitized_array = sanitized_array.intersection(board.roles_array) ### This may slow the query down
        end

        self[:roles] = sanitized_array.join(";;")
      else
        raise "invalid behaviour"
      end
    end

    def roles_array
      self[:roles]&.split(";;") || []
    end

  end
end

app/models/pairer/person.rb
module Pairer
  class Person < ApplicationRecord
    belongs_to :board, class_name: "Pairer::Board"

    validates :name, presence: true, uniqueness: {scope: :board_id, case_sensitive: false}
  end
end

app/controllers/pairer/application_controller.rb
module Pairer
  class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception

    helper_method :signed_in?

    def robots
      str = <<~STR
        User-agent: *
        Disallow: /
      STR

      render plain: str, layout: false, content_type: 'text/plain'
    end

    def render_404
      if request.format.html?
        render "pairer/exceptions/show", status: 404
      else
        render plain: "404 Not Found", status: 404
      end
    end

    def signed_in?
      if session[:pairer_current_org_id].present?
        Pairer.config.allowed_org_ids.collect(&:downcase).include?(session[:pairer_current_org_id].downcase)
      end
    end

  end
end

app/controllers/pairer/boards_controller.rb
require_dependency "pairer/application_controller"

module Pairer
  class BoardsController < ApplicationController
    before_action do
      if !signed_in?
        redirect_to sign_in_path
      end
    end

    before_action :get_board, except: [:index, :new, :create]

    helper_method :people_by_id

    def index
      if params[:password].present?
        @board = Pairer::Board.find_by(org_id: session[:pairer_current_org_id], password: params[:password])

        if @board
          session[:pairer_current_board_id] = @board.to_param
          redirect_to action: :show, id: session[:pairer_current_board_id]
        else
          flash.now.alert = "Board not found."

          render
        end
      end
    end

    def create
      @board = Pairer::Board.new(password: params[:password], org_id: session[:pairer_current_org_id])

      if @board.save
        session[:pairer_current_board_id] = @board.to_param
        flash.notice = "Board created."
        redirect_to(action: :show, id: @board.to_param)
      else
        other_board = Pairer::Board.find_by(org_id: session[:pairer_current_org_id], password: params[:password])

        if other_board
          session[:pairer_current_board_id] = other_board.to_param
          flash.notice = "Existing board found."
          redirect_to(action: :show, id: other_board.to_param)
        else
          flash.alert = "Board not saved. Please choose a different password."
          redirect_to(action: :index)
        end
      end
    end

    def show
      session_key = :pairer_board_access_list

      access_list = session[session_key] || {}

      access_list[@board.public_id] = Time.now.to_s

      session[session_key] = access_list
    end

    def update
      if params[:add_role_name]
        params[:board] = {}
        params[:board][:roles] = @board.roles_array + [params[:add_role_name]]
      elsif params[:remove_role_name]
        params[:board] = {}
        params[:board][:roles] = @board.roles_array - [params[:remove_role_name]]
      end

      if params[:clear_board]
        @board.groups.destroy_all
        @board.update!(current_iteration_number: 0)
        saved = true
      else
        saved = @board.update(params.require(:board).permit(:name, :password, :group_size, :num_iterations_to_track, roles: []))
      end

      if saved
        if params.dig(:board, :password)
          flash.notice = "Password updated."
        else
          flash.notice = "Board updated."
        end

        broadcast_changes
      else
        if @board.errors[:num_iterations_to_track].present?
          flash.alert = "Number of Iterations to Track #{@board.errors[:num_iterations_to_track].first}"
        else
          flash.alert = "Board not saved."
        end
      end

      redirect_to(action: :show)
    end

    def destroy
      @board.destroy!
      flash.notice = "Board deleted."
      redirect_to(action: :index)
    end

    def shuffle
      @board.shuffle!
      broadcast_changes
      redirect_to(action: :show)
    end

    def create_person
      @person = @board.people.create(name: params[:name])

      if @person.persisted?
        broadcast_changes
      end

      if request.format.js?
        render_js_page_replace
      else
        redirect_to(action: :show)
      end
    end

    def lock_person
      @person = @board.people.find_by!(public_id: params.require(:person_id))

      @person.update!(locked: params[:lock] == "true")
      broadcast_changes

      if request.format.js?
        render_js_page_replace
      else
        redirect_to(action: :show)
      end
    end

    def delete_person
      @person = @board.people.find_by!(public_id: params.require(:person_id))

      @person.destroy!
      broadcast_changes

      redirect_to(action: :show)
    end

    def create_group
      @group = @board.groups.create!(board_iteration_number: @board.current_iteration_number)
      broadcast_changes

      if request.format.js?
        render_js_page_replace
      else
        redirect_to(action: :show)
      end
    end

    def lock_group
      @group = @board.current_groups.find_by!(public_id: params.require(:group_id))

      @person.update!(locked: params[:lock] == "true")
      broadcast_changes

      if request.format.js?
        render_js_page_replace
      else
        redirect_to(action: :show)
      end
    end

    def delete_group
      @group = @board.current_groups.find_by!(public_id: params.require(:group_id))

      @group.destroy!
      broadcast_changes

      if request.format.js?
        render_js_page_replace
      else
        redirect_to(action: :show)
      end
    end

    def update_group
      @group = @board.current_groups.find_by!(public_id: params.require(:group_id))

      person_ids_was = @group.person_ids_array
      roles_was = @group.roles_array

      attrs = {
        person_ids: (params[:person_ids] if params[:person_ids].present?),
        roles: (params[:roles] if params[:roles].present?),
      }.compact

      @group.assign_attributes(attrs)

      new_person_ids = @group.person_ids_array - person_ids_was
      new_roles = @group.roles_array - roles_was

      if @group.changed?
        changed = true

        if params[:removal] == "true"
          @group.save!
        else
          ActiveRecord::Base.transaction do
            @group.save!

            if new_person_ids.any?
              @board.current_groups.detect do |g|
                next if g.id == @group.id

                if g.person_ids_array.intersection(new_person_ids).any?
                  g.person_ids = g.person_ids_array - @group.person_ids_array
                  g.save!
                  true
                end
              end
            end

            if new_roles.any?
              @board.current_groups.detect do |g|
                next if g.id == @group.id

                if g.roles_array.intersection(new_roles).any?
                  g.roles = g.roles_array - @group.roles_array
                  g.save!
                  true
                end
              end
            end
          end
        end

        broadcast_changes
      end

      if request.format.js?
        render_js_page_replace
      else
        redirect_to(action: :show)
      end
    end

    private

    def get_board
      if session[:pairer_current_board_id].blank?
        redirect_to(action: :index)
      end

      @board = Pairer::Board
        .includes(:people, :groups)
        .find_by!(org_id: session[:pairer_current_org_id], public_id: params[:id])
    end

    def people_by_id
      @people_by_id ||= @board.people.map{|x| [x.to_param, x] }.to_h
    end

    def broadcast_changes
      ActionCable.server.broadcast(
        "board_#{@board.public_id}",
        {
          action: "reload",
          identifier: session[:pairer_user_id],
        }
      )
    end

    include ActionView::Helpers::JavaScriptHelper
    def render_js_page_replace
      get_board

      js_page_content = escape_javascript(render_to_string "pairer/boards/show", layout: false)

      javascript = <<~STR
        $("#page-content").html("#{js_page_content}");
      STR

      render(js: javascript)
    end

  end
end

app/controllers/pairer/main_controller.rb
require_dependency "pairer/application_controller"

module Pairer
  class MainController < ApplicationController
    before_action except: [:sign_in] do
      if !signed_in?
        redirect_to action: :sign_in
      end
    end

    before_action :get_board, except: [:index, :new, :create, :sign_in, :sign_out]

    def index
      if params[:password].present?
        @board = Pairer::Board.find_by(org_name: session[:current_org_name], password: params[:password])
        if @board
          session[:current_board_id] = @board.to_param
          redirect_to action: :show, id: session[:current_board_id]
        else
          flash.now.alert = "Board not found."
          render
        end
      end
    end

    def sign_in
      if request.method == "GET"
        if signed_in?
          redirect_to(action: :index)
        end

      elsif request.method == "POST"
        if Pairer.allowed_org_names.include?(params[:org_name]&.downcase)
          session[:current_org_name] = params[:org_name].downcase
          redirect_to(action: :index)
        end
      end
    end

    def sign_out
      session.delete(:current_org_name)
      session.delete(:current_board_id)
      flash.notice = "Signed out"
      redirect_to(action: :sign_in)
    end

    def create
      @board = Pairer::Board.new(password: params[:password], org_name: session[:current_org_name])

      if @board.save
        session[:current_board_id] = @board.to_param
        flash.notice = "Board created."
        redirect_to(action: :show, id: @board.to_param)
      else
        other_board = Pairer::Board.find_by(org_name: session[:current_org_name], password: params[:password])

        if other_board
          session[:current_board_id] = other_board.to_param
          flash.notice = "Existing board found."
          redirect_to(action: :show, id: other_board.to_param)
        else
          flash.alert = "Board not saved. Please choose a different password."
          redirect_to(action: :index)
        end
      end
    end

    def show
    end

    def update
      if params[:add_role_name]
        params[:board] = {}
        params[:board][:roles] = @board.roles_array + [params[:add_role_name]]
      elsif params[:remove_role_name]
        params[:board] = {}
        params[:board][:roles] = @board.roles_array - [params[:remove_role_name]]
        Rails.logger.debug("*"*1000)
        Rails.logger.debug params[:board][:roles]
      end

      if params[:clear_board]
        @board.groups.destroy_all
        @board.update!(current_iteration_number: 0)
        saved = true
      else
        saved = @board.update(params.require(:board).permit(:name, :password, :group_size, :num_iterations_to_track, roles: []))
      end
      
      if saved
        if params.dig(:board, :password)
          flash.notice = "Password updated."
        elsif
          flash.notice = "Board updated."
        end
      else
        flash.alert = "Board not saved."
      end

      redirect_to(action: :show)
    end

    def destroy
      @board.destroy!
      flash.notice = "Board deleted."
      redirect_to(action: :index)
    end

    def shuffle
      @board.shuffle!
      redirect_to(action: :show)
    end

    def create_person
      @board.people.create(name: params[:name])
      redirect_to(action: :show)
    end

    def lock_person
      @board.people.find_by!(public_id: params.require(:person_id)).toggle!(:locked)
      redirect_to(action: :show)
    end

    def delete_person
      @board.people.find_by!(public_id: params.require(:person_id)).destroy!
      redirect_to(action: :show)
    end

    def create_group
      @board.groups.create!(board_iteration_number: @board.current_iteration_number)
      redirect_to(action: :show)
    end

    def lock_group
      @board.groups.find_by!(public_id: params.require(:group_id)).toggle!(:locked)
      redirect_to(action: :show)
    end

    def delete_group
      @board.groups.find_by!(public_id: params.require(:group_id)).destroy!
      redirect_to(action: :show)
    end

    def update_group
      @group = @board.groups.find_by!(public_id: params.require(:group_id))

      attrs = {
        person_ids: (params[:person_ids] if params[:person_ids].present?),
        roles: (params[:roles] if params[:roles].present?),
      }.compact
      
      @group.update!(attrs)

      if request.format.js?
        render inline: "", layout: "pairer/application"
      else
        redirect_to(action: :show)
      end
    end

    private

    def get_board
      if session[:current_board_id].blank?
        redirect_to(action: :index)
      end

      @board = Pairer::Board.find_by!(org_name: session[:current_org_name], public_id: params[:id])
    end

  end
end

app/controllers/pairer/sessions_controller.rb
require_dependency "pairer/application_controller"

module Pairer
  class SessionsController < ApplicationController

    def sign_in
      if request.method == "GET"
        if signed_in?
          redirect_to boards_path
        end

      elsif request.method == "POST"
        if Pairer.config.allowed_org_ids.include?(params[:org_id]&.downcase)
          session[:pairer_current_org_id] = params[:org_id].downcase
          session[:pairer_user_id] = "#{session[:pairer_current_org_id]}_#{SecureRandom.uuid}"
          redirect_to boards_path
        end
      end
    end

    def sign_out
      if !signed_in?
        redirect_to action: :sign_in
      else
        session.delete(:pairer_current_org_id)
        session.delete(:pairer_current_board_id)
        session.delete(:pairer_user_id)
        flash.notice = "Signed out"
        redirect_to sign_in_path
      end
    end

  end
end

app/helpers/pairer/application_helper.rb
module Pairer
  module ApplicationHelper

    ASSET_VERSION = `git show -s --format=%ci`.parameterize.freeze
    def custom_asset_path(path)
      "#{path}?v=#{Rails.env.development? ? Time.now.to_i : ASSET_VERSION}"
    end

  end
end

app/views/pairer/main/_person.html.slim
span.person data-person-id=person.public_id
  = person.name

  = link_to lock_person_board_path(@board, person_id: person), data: {method: :post}, class: 'btn btn-xs btn-default space-left2', title: "Lock Person" do
    i class=(person.locked? ? 'icon-lock' : 'icon-unlock')

  span.space-left
    = link_to delete_person_board_path(@board, person_id: person), data: {method: :delete, confirm: "Are you sure you want to delete person '#{person.name}'?"}, title: "Delete Person", class: 'btn btn-xs btn-danger' do
      i.icon-trash

app/views/pairer/main/_role.html.slim
span.role data-role-name=role 
  = role

  span.space-left2
    = link_to board_path(@board, remove_role_name: role), data: {method: :patch, confirm: "Are you sure you want to remove '#{role}' role ?"}, title: "Delete Role", class: 'btn btn-xs btn-danger' do
      i.icon-trash

app/views/pairer/main/show.html.slim
.pull-right
  .text-right
    button.btn.btn-default.btn-sm.space-right2 type="button" onclick=("alert('Board password is: #{@board.password}')") View Password
    button.btn.btn-default.btn-sm.space-right2 type="button" onclick=("$('.password-form').toggle()") Change Password
    = link_to "Delete Board", board_path(@board), class: "btn btn-danger btn-sm", data: {method: :delete, confirm: "Are you sure you want to delete the board?"}

  = form_tag board_path(@board), method: :patch, class: 'form-inline password-form', style: 'display:none' do
    h3 Change Board Password

    label Board Password
    input.form-control.password name="board[password]" type="password" value=@board.password style="width: 100px;"
    i.icon-eye-open.space-left onclick="$('input.password').attr('type', ($('input.password').attr('type') == 'text' ? 'password' : 'text'))"

    span.space-left2
      button.btn.btn-xs.btn-success type="submit" Update

h1.space-above
  = "Board: #{@board.name}"
  = link_to "Shuffle", shuffle_board_path(@board), class: "btn btn-success btn-sm space-left4", data: {method: :post}

= form_tag board_path(@board), method: :patch, class: 'form-inline' do
  /h3 Edit Board

  - if @board.errors.any?
    .well.well-sm
      div.bold Errors:
      = @board.errors.full_messages.join("<br>").html_safe
  
  div
    label Board Name
    input.form-control.change-submit name="board[name]" value=@board.name style="width: 150px;"

    span.space-left3
      label Group Size
      input.form-control.change-submit name="board[group_size]" value=@board.group_size style="width: 50px;"

    span.space-left3
      label Number of Iterations to Track
      input.form-control.change-submit name="board[num_iterations_to_track]" value=@board.num_iterations_to_track style="width: 50px;"

.row
  .col-sm-9
    h3 
      .pull-left.space-right2 Groups
      = form_tag create_group_board_path(@board) do
        button.btn.btn-xs.btn-success type="submit" Add

    table.table-bordered.table
      thead
        th
        th style="width: 50%" People
        th Roles
      tbody
        - people_by_id = @board.people.map{|x| [x.to_param, x] }.to_h

        - used_person_ids = @board.current_groups.flat_map{|x| x.person_ids_array }

        - used_roles = @board.current_groups.flat_map{|x| x.roles_array }

        - @board.current_groups.each do |group|
          tr
            td
              div
                = link_to lock_group_board_path(@board, group_id: group), data: {method: :post}, class: 'btn btn-xs btn-default', title: "#{group.locked? ? "Unlock" : "Lock"} Group" do
                  i class=(group.locked? ? 'icon-lock' : 'icon-unlock')

              .space-above2
                = link_to delete_group_board_path(@board, group_id: group), data: {method: :delete, confirm: "Are you sure you want to delete this group?"}, class: 'btn btn-xs btn-danger', title: "Delete Group" do
                  i.icon-trash

            td.person-list data-group-id=group.public_id
              - group.person_ids_array.each do |person_public_id|
                - person = people_by_id[person_public_id]
                - if person
                  = render 'person', person: person

            td.roles-list data-group-id=group.public_id
              - group.roles_array.each do |role|
                = render 'role', role: role

    h3 
      .pull-left Stats
      = link_to "Reset Stats and Groups", board_path(@board, clear_board: true), class: 'btn btn-danger btn-sm space-left2', data: {method: :patch}
    - stats = @board.stats

    - if stats.empty?
      p Cannot show stats with only 1 person on the board
    - else
      ul
        - @board.stats.each do |stat|
          li = stat

    - if Rails.env.development?
      = "Current Groups: #{@board.current_groups.size}"
      br
      = "Current Groups Iteration Numbers: #{@board.current_groups.collect(&:board_iteration_number).uniq.join(", ")}"
      br
      = "Tracked Groups: #{@board.tracked_groups.size}"
      br
      = "Tracked Groups Iteration Numbers: #{@board.tracked_groups.collect(&:board_iteration_number).uniq.join(", ")}"

  .col-sm-3.well
    h3 
      .pull-left.space-right2 Roles

      = form_tag board_path(@board), method: :patch, class: 'form-inline space-below space-left3' do
        = text_field_tag :add_role_name, nil, placeholder: "Role Name", style: "width: 150px;", class: 'form-control'

        span.space-left
          button.btn.btn-sm.btn-success type="submit" Add

    .roles-list style="min-height: 25px;"
      - group_roles = @board.current_groups.flat_map(&:roles_array)
      - @board.roles_array.select{|x| group_roles.exclude?(x) }.each do |role|
        = render 'role', role: role

    h3.space-above5
      .pull-left.space-right4 People

      = form_tag create_person_board_path(@board), class: 'form-inline space-below space-left3' do
        = text_field_tag :name, nil, placeholder: "Name", style: "width: 150px;", class: 'form-control'

        span.space-left
          button.btn.btn-sm.btn-success type="submit" Add

    .person-list style="min-height: 40px;"
      - group_person_ids = @board.current_groups.flat_map(&:person_ids_array)

      - @board.people.select{|x| group_person_ids.exclude?(x.public_id) }.sort_by{|x| x.name }.each do |person|
        = render 'person', person: person

css:
  .role, 
  .person{
    display: inline-block;
    border: 1px solid black;
    border-radius: 4px;
    padding: 0px 10px 3px 10px;
    margin: 5px 5px;
    line-height: 40px;
    cursor: grab;
  }

javascript:
  $(function(){

    $('.change-submit').on('change', function(){
      var item = $(this);
      setTimeout(function(){
        if(item.val() == "" && item.is('select[multiple]')){
          item.attr('disabled', true);
          $("<input name='"+item.attr('name')+"' value='"+item.val()+"' />").insertBefore(item);
        }
        item.closest("form").submit();
      }, 1);
    });

    $(".person-list").sortable({
      connectWith: ".person-list",
      items: "> .person",
      revert: true,
      update: function(){
        var group_id = $(this).data('group-id');
        var prev_person_ids = $(this).data('prev-person-ids');

        var $el = $(this);

        if(group_id){
          var person_ids = []

          $el.find('.person').each(function(i, item){
            person_ids.push($(item).data('person-id'))
          });

          if(!equals(prev_person_ids, person_ids)){
            if(person_ids.length === 0){
              person_ids.push(""); // to ensure empty array value make the params
            }

            $.ajax({
              url: "#{update_group_board_path(@board, format: :js)}",
              method: "POST",
              data: {group_id: group_id, person_ids: person_ids},
            }).done(function(){
              $el.data('prev-person-ids', person_ids);
            });
          }
        }
      },
    });

    $(".roles-list").sortable({
      connectWith: ".roles-list",
      items: "> .role",
      revert: true,
      update: function(){
        var group_id = $(this).data('group-id');
        var prev_roles = $(this).data('prev-roles');

        $el = $(this);

        if(group_id){
          var roles = [];

          $el.find('.role').each(function(i, item){
            roles.push($(item).data('role-name'))
          });

          if(!equals(prev_roles, roles)){
            if(roles.length === 0){
              roles.push(""); // to ensure empty array value make the params
            }

            $.ajax({
              url: "#{update_group_board_path(@board, format: :js)}",
              method: "POST",
              data: {group_id: group_id, roles: roles},
            }).done(function(){
              $el.data('prev-roles', roles);
            });
          }
        }
      },
    });

  });